// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtPCOVzNEcGUatQjeWqXSA6CVzFZ9v798',
    appId: '1:754558261114:android:4ed6c91655e14e1e5428c3',
    messagingSenderId: '754558261114',
    projectId: 'search-4e7b2',
    storageBucket: 'search-4e7b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5lE22zfpLHLYX7Ko9V_Zcgz5tSoGaprs',
    appId: '1:754558261114:ios:5f27e4ddc94792675428c3',
    messagingSenderId: '754558261114',
    projectId: 'search-4e7b2',
    storageBucket: 'search-4e7b2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSearchCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5lE22zfpLHLYX7Ko9V_Zcgz5tSoGaprs',
    appId: '1:754558261114:ios:5f27e4ddc94792675428c3',
    messagingSenderId: '754558261114',
    projectId: 'search-4e7b2',
    storageBucket: 'search-4e7b2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSearchCrud',
  );
}
